// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVpXKWFvlI9wjA0haJ27_H3w3p5oElv0',
    appId: '1:49601388756:web:7c4d1b9ea16c64c4041b41',
    messagingSenderId: '49601388756',
    projectId: 'do-an-ef3cd',
    authDomain: 'do-an-ef3cd.firebaseapp.com',
    storageBucket: 'do-an-ef3cd.firebasestorage.app',
    measurementId: 'G-XGEJJYF24T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgJoYVP8fksc5KmmcWcpRBgwXenCu8oY',
    appId: '1:49601388756:android:0ba793552f416ccb041b41',
    messagingSenderId: '49601388756',
    projectId: 'do-an-ef3cd',
    storageBucket: 'do-an-ef3cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNmFlNlDLE6xhe5cs4GyeEdepn0P_ZuY',
    appId: '1:49601388756:ios:3cdfa8007ffc31a6041b41',
    messagingSenderId: '49601388756',
    projectId: 'do-an-ef3cd',
    storageBucket: 'do-an-ef3cd.firebasestorage.app',
    iosBundleId: 'com.example.appembe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNmFlNlDLE6xhe5cs4GyeEdepn0P_ZuY',
    appId: '1:49601388756:ios:3cdfa8007ffc31a6041b41',
    messagingSenderId: '49601388756',
    projectId: 'do-an-ef3cd',
    storageBucket: 'do-an-ef3cd.firebasestorage.app',
    iosBundleId: 'com.example.appembe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVpXKWFvlI9wjA0haJ27_H3w3p5oElv0',
    appId: '1:49601388756:web:bcd05536e05548f8041b41',
    messagingSenderId: '49601388756',
    projectId: 'do-an-ef3cd',
    authDomain: 'do-an-ef3cd.firebaseapp.com',
    storageBucket: 'do-an-ef3cd.firebasestorage.app',
    measurementId: 'G-T0J7R10STV',
  );
}
